### ISSUE TITLE
FileMaker version support

### ISSUE THREAD

**Issue by kjohnston** [lardawge/rfm#8]
Great gem, we've been using it for a few years now to talk to FM10..12 and are looking at upgrading to 13..14.  Does `rfm` work with v13 and/or v14?

**Comment by lardawge** [comment]
I have not personally used it with either of those version but given the snails pace at which filemaker innovates, I would be shocked if it didn't. Would be easy enough to test.

**Comment by kjohnston** [comment]
@lardawge, thank you for your prompt response and continued support of this project.

**Comment by shivamd** [comment]
I can confirm that this does work. 
And yes thanks for the great gem!

**Comment by kjohnston** [comment]
@shivamd, what version are you using?  We're going to be testing against 14 next week.

**Comment by kjohnston** [comment]
We had switched to the [gingo-rfm](https://github.com/ginjo/rfm) fork a while back and ended up hanging with it, and going to the latest version, and have been using it successfully against FM14 for the last couple of weeks.
